[package]
name = "TaskBeam"
version = "0.1.0"
edition = "2024"

[dependencies]
bellman = "0.14.0"
bls12_381 = "0.8.0"
ff = "0.13.1"
pairing = "0.23.0"
rand = "0.8.5"
rand_core = "0.6.4"
sha2 = "0.10.9"

